'use client';
import {useEffect,useMemo,useState} from 'react';
import UtilityNav from '../utility-nav';
type Registry={media:{id:string;foreign:boolean;categories:string[];entities:string[];locations:{region:string}[]}[];entities:Record<string,{name:string}>;regions:{id:string;name:string}[]};
type Contacts={registrationDateAvailable:boolean;notes:Record<string,string>;emails:GroupSet;phones:GroupSet;addresses:GroupSet};
type GroupSet={duplicateGroups:number;mediaInGroups:number;groups:{label:string;count:number;mediaIds:string[]}[]};
const topics=[['geography','Географія','Geography','Розподіл реєстрацій за областями та окремо іноземні медіа.','Distribution by region and foreign media.'],['categories','Види діяльності','Activity types','Структура реєстру за видами медійної діяльності.','Registry structure by media activity.'],['registrants','Портфелі реєстрантів','Registrant portfolios','Суб’єкти з найбільшою кількістю медіаідентифікаторів.','Entities with the largest numbers of media identifiers.'],['registration-date','Дата реєстрації','Registration date','Наявність даних для часової динаміки.','Whether the source supports time-series analysis.'],['shared-contacts','Збіги контактів','Shared contacts','Повторювані email, телефони й адреси як сигнали для перевірки.','Repeated emails, phones and addresses as review signals.']] as const;
export function AnalyticsIndex({locale}:{locale:'uk'|'en'}){const en=locale==='en';return <><UtilityNav locale={locale} profile path="/analytics"/><main className="analysis-page"><p className="eyebrow">{en?'ANALYTICAL CONTENTS':'ЗМІСТ АНАЛІТИКИ'}</p><h1>{en?'Explore the registry':'Досліджуйте реєстр'}</h1><p className="analysis-lead">{en?'Open one analytical aspect at a time. Each page explains the limits of the source data.':'Відкривайте по одному аналітичному аспекту. На кожній сторінці пояснено обмеження джерела.'}</p><div className="analysis-toc">{topics.map(t=><a href={(en?'/en':'')+'/analytics/'+t[0]} key={t[0]}><small>{String(topics.indexOf(t)+1).padStart(2,'0')}</small><h2>{en?t[2]:t[1]}</h2><p>{en?t[4]:t[3]}</p><b>→</b></a>)}</div><Correction en={en}/></main></>}
export function AnalyticsTopic({locale,topic}:{locale:'uk'|'en';topic:string}){const en=locale==='en';const [registry,setRegistry]=useState<Registry|null>(null),[contacts,setContacts]=useState<Contacts|null>(null);useEffect(()=>{Promise.all([fetch('/data/registry.json').then(r=>r.json()),fetch('/data/contact-analytics.json').then(r=>r.json())]).then(([a,b])=>{setRegistry(a as Registry);setContacts(b as Contacts)})},[]);const analysis=useMemo(()=>registry&&build(registry,topic),[registry,topic]);return <><UtilityNav locale={locale} profile path={"/analytics/"+topic}/><main className="analysis-page"><a className="analysis-back" href={(en?'/en':'')+'/analytics'}>{en?'← Analytical contents':'← Зміст аналітики'}</a><p className="eyebrow">{en?'MEDIA REGISTRY ANALYTICS':'АНАЛІТИКА МЕДІАРЕЄСТРУ'}</p><h1>{en?(topics.find(t=>t[0]===topic)?.[2]||'Analytics'):(topics.find(t=>t[0]===topic)?.[1]||'Аналітика')}</h1>{!registry||!contacts?<p>{en?'Loading data…':'Завантажуємо дані…'}</p>:topic==='shared-contacts'?<ContactView data={contacts} en={en}/>:topic==='registration-date'?<DateView data={contacts} en={en}/>:<RankView rows={analysis||[]} en={en} topic={topic}/>}<Correction en={en}/></main></>}
function build(d:Registry,topic:string){if(topic==='geography'){const c:Record<string,number>={};d.media.forEach(m=>{if(m.foreign)c['Іноземні медіа']=(c['Іноземні медіа']||0)+1;else new Set(m.locations.map(x=>x.region)).forEach(r=>c[d.regions.find(x=>x.id===r)?.name||r]=(c[d.regions.find(x=>x.id===r)?.name||r]||0)+1)});return Object.entries(c).sort((a,b)=>b[1]-a[1])}if(topic==='categories'){const c:Record<string,number>={};d.media.forEach(m=>m.categories.forEach(x=>c[x]=(c[x]||0)+1));return Object.entries(c).sort((a,b)=>b[1]-a[1])}const c:Record<string,number>={};d.media.forEach(m=>m.entities.forEach(x=>c[x]=(c[x]||0)+1));return Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,100).map(([x,n])=>[d.entities[x]?.name||x,n] as [string,number])}
function RankView({rows,en,topic}:{rows:[string,number][];en:boolean;topic:string}){const max=rows[0]?.[1]||1;return <><p className="analysis-lead">{topic==='registrants'?(en?'A shared registrant does not by itself prove common editorial control or ownership.':'Спільний реєстрант сам по собі не доводить спільного редакційного контролю чи власності.'):(en?'Counts may overlap when one identifier has several records.':'Показники можуть перетинатися, якщо один ідентифікатор має кілька записів.')}</p><div className="analysis-ranking">{rows.map(([label,n])=><div key={label}><span>{label}</span><strong>{n.toLocaleString(en?'en-US':'uk-UA')}</strong><i style={{width:(n/max*100)+'%'}}/></div>)}</div></>}
function DateView({data,en}:{data:Contacts;en:boolean}){return <div className="analysis-note"><strong>{en?'The source does not contain registration dates':'У джерелі немає дат реєстрації'}</strong><p>{en?'The workbook only states that the registry is current as of 1 August 2026. A registration date cannot be reliably inferred from the identifier, so the atlas does not fabricate a timeline.':'Таблиця лише зазначає, що реєстр актуальний станом на 01.08.2026. Надійно вивести дату з ідентифікатора не можна, тому атлас не створює вигадану часову динаміку.'}</p></div>}
function ContactView({data,en}:{data:Contacts;en:boolean}){return <><p className="analysis-lead">{en?'Matches are leads for further research, not proof of common ownership. Contact values are masked.':'Збіги — це сигнали для подальшої перевірки, а не доказ спільної власності. Значення контактів замасковані.'}</p>{([['emails',data.emails],['phones',data.phones],['addresses',data.addresses]] as const).map(([key,set])=><section className="contact-section" key={key}><h2>{en?({emails:'Matching emails',phones:'Matching phones',addresses:'Matching addresses'}[key]):({emails:'Збіги email',phones:'Збіги телефонів',addresses:'Збіги адрес'}[key])}</h2><p><strong>{set.duplicateGroups}</strong> {en?'duplicate groups covering':'груп збігів, що охоплюють'} <strong>{set.mediaInGroups}</strong> {en?'media identifiers':'медіаідентифікаторів'}</p>{set.groups.slice(0,50).map((g,i)=><details key={i}><summary>{g.label} · {g.count}</summary><p>{g.mediaIds.join(' · ')}</p></details>)}</section>)}</>}
function Correction({en}:{en:boolean}){return <aside className="correction-box"><strong>{en?'Found an error or inaccuracy?':'Побачили помилку або неточність?'}</strong><a href="mailto:info@promedia.report">info@promedia.report</a></aside>}



