'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import UtilityNav from '../../utility-nav';
type Article={title:string;url:string;publishedAt?:string;excerpt?:string};
type ProfileData={id:string;name:string;date:string;newsIds:string[];grouping:string;community:null|{id:string;website:string;description:string};entities:Record<string,{name:string;code:string}>;regions:{id:string;name:string}[];media:{id:string;names:string[];categories:string[];locations:{city:string;region:string}[];technologies:string[];details:{row:number;city:string;region:string;channel:string;frequency:string;territory:string;note:string}[]}[]};
const source='https://webportal.nrada.gov.ua/derzhavnyj-reyestr-sub-yektiv-informatsijnoyi-diyalnosti-u-sferi-telebachennya-i-radiomovlennya/';
const safeUrl=(s:string)=>{try{const u=new URL(s);return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch{return ''}};
export default function Profile({id,locale}:{id:string;locale:'uk'|'en'}){
 const en=locale==='en',tr=(uk:string,english:string)=>en?english:uk;
 const [profile,setProfile]=useState<ProfileData|null>(null),[error,setError]=useState(''),[news,setNews]=useState<Article[]>([]),[newsState,setNewsState]=useState('loading'),[attempt,setAttempt]=useState(0);
 useEffect(()=>{document.documentElement.lang=locale},[locale]);
 useEffect(()=>{const c=new AbortController();setProfile(null);setError('');if(!/^atlas-[a-z0-9-]+$/.test(id)){setError('Такої сторінки немає.');return}const bucket=id.slice(6,7);fetch('/data/brand-buckets/'+encodeURIComponent(bucket)+'.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error(r.status===404?'Такої сторінки немає.':'Не вдалося завантажити сторінку.');return r.json()}).then(v=>{const p=(v as Record<string,ProfileData>)[id];if(!p||p.id!==id||!Array.isArray(p.media)||!Array.isArray(p.newsIds))throw Error('Такої сторінки немає.');setProfile(p);document.title=p.name+(en?' — Media Atlas':' — Атлас Меда')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[id]);
 useEffect(()=>{if(!profile)return;const c=new AbortController();setNews([]);setNewsState('loading');Promise.allSettled(profile.newsIds.map(mediaId=>fetch('https://news.promedia.report/api/articles?mediaId='+encodeURIComponent(mediaId)+'&limit=12',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('News unavailable');return r.json()}).then(v=>{const items=(v as {items?:Article[]}).items;if(!Array.isArray(items))throw Error('Invalid news');return items}))).then(results=>{if(c.signal.aborted)return;const items=results.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(a=>typeof a.title==='string'&&typeof a.url==='string'&&safeUrl(a.url).startsWith('https://news.promedia.report/article/'));const unique=[...new Map(items.map(a=>[a.url,a])).values()].sort((a,b)=>(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0)).slice(0,12);setNews(unique);setNewsState(results.some(r=>r.status==='rejected')?(unique.length?'partial':'error'):'ready')});return()=>c.abort()},[profile,attempt]);
 return <><UtilityNav locale={locale} profile mediaId={id}/><main className="profile-page">{error?<section className="empty"><h1>{error}</h1><a href={en?'/en':'/'}>{tr('Повернутися до каталогу','Return to the directory')}</a></section>:!profile?<p role="status">{tr('Завантажуємо сторінку медіа…','Loading media page…')}</p>:<><p className="eyebrow">{tr('ПУБЛІЧНА СТОРІНКА МЕДІАБРЕНДУ','PUBLIC MEDIA BRAND PAGE')}</p><h1>{profile.name}</h1><div className="profile-summary"><span>{profile.media.length} {tr('реєстрацій','registrations')}</span><span>{new Set(profile.media.flatMap(m=>m.categories)).size} {tr('видів діяльності','activity types')}</span><span>{tr('Реєстр на','Registry as of')} {profile.date}</span></div>{profile.community&&<><p className="profile-lead">{profile.community.description}</p><div className="profile-links">{safeUrl(profile.community.website)&&<a href={safeUrl(profile.community.website)} target="_blank" rel="noreferrer">{tr('Сайт медіа ↗','Media website ↗')}</a>}<a href={'https://communities.promedia.report/media/?id='+encodeURIComponent(profile.community.id)}>{tr('Спільнота медіа ↗','Media community ↗')}</a></div></>}{!profile.community&&<p className="profile-description-missing">{tr('Перевірений опис із відкритого джерела ще не додано. Знаєте офіційний сайт або надійне джерело? Напишіть на info@promedia.report.','A verified description from an open source has not been added yet. Know the official website or a reliable source? Email info@promedia.report.')}</p>}
 <div className="profile-grid"><section className="profile-records"><h2>{tr('Реєстрації цього бренду','Registrations under this brand')}</h2><p className="help">{tr('Кожен ідентифікатор збережено окремо разом із записами джерела.','Each identifier is preserved separately with its source records.')}</p>{profile.media.map(m=><details key={m.id} className="registration"><summary><b>{m.id}</b><span>{m.categories.join('; ')}</span></summary><h3>{tr('Назва в реєстрі','Name in the registry')}</h3><p>{m.names.join(' / ')||'Не зазначено'}</p><h3>{tr('Місцезнаходження','Location')}</h3><p>{m.locations.map(l=>l.city+', '+(profile.regions.find(r=>r.id===l.region)?.name||l.region)).join('; ')||'Іноземне медіа'}</p><h3>{tr('Технологія / вид медіа','Technology / media type')}</h3><p>{m.technologies.join('; ')||'Не зазначено'}</p>{m.details.map((d,i)=><details className="source-record" key={i}><summary>Рядок {d.row}{d.city?' · '+d.city:''}</summary>{Object.entries({'Населений пункт':d.city,'Область':d.region,'Канал':d.channel,'Частота':d.frequency,'Територія':d.territory,'Примітка':d.note}).filter(([,v])=>v).map(([k,v])=><p key={k}><b>{k}: </b>{v}</p>)}</details>)}</details>)}<h2>{tr('Реєстранти','Registrants')}</h2>{Object.entries(profile.entities).map(([e,v])=><article key={e} className="registrant"><h3>{v.name}</h3>{v.code&&<p>ЄДРПОУ: {v.code}</p>}</article>)}<details className="method"><summary>{tr('Як об’єднано реєстрації','How registrations were grouped')}</summary><p>{profile.grouping}</p><p>Однаковий власник сам по собі не об’єднує різні бренди. Схожі назви різних реєстрантів залишаються окремими до перевірки. Це сторінка за даними реєстру, а не підтвердження фактичної роботи чи структури власності.</p><a href={source}>Перевірити першоджерело ↗</a></details></section>
 <aside className="profile-news"><p className="eyebrow">{tr('НОВИНИ ПРО ЦЕ МЕДІА','NEWS ABOUT THIS MEDIA BRAND')}</p><h2>{tr('У фокусі ПроМедіа','ProMedia coverage')}</h2><p className="help">{tr('Матеріали, які редакція ПроМедіа пов’язала з цим брендом.','Stories that ProMedia editors linked to this brand.')}</p>{newsState==='loading'&&<p role="status">{tr('Завантажуємо новини…','Loading news…')}</p>}{newsState==='ready'&&!news.length&&<p className="news-empty">{tr('Пов’язаних публікацій поки немає.','There are no related stories yet.')}</p>}{(newsState==='error'||newsState==='partial')&&<div role="status"><p>{newsState==='partial'?'Частина новин тимчасово недоступна.':'Не вдалося завантажити новини.'}</p><Button variant="outline" onClick={()=>setAttempt(a=>a+1)}>Спробувати ще раз</Button></div>}{news.map(a=><article className="brand-news-item" key={a.url}>{a.publishedAt&&Number.isFinite(Date.parse(a.publishedAt))&&<time dateTime={a.publishedAt}>{new Date(a.publishedAt).toLocaleDateString('uk-UA')}</time>}<h3><a href={a.url} target="_blank" rel="noreferrer">{a.title} ↗</a></h3>{a.excerpt&&<p>{a.excerpt}</p>}</article>)}<a href="https://news.promedia.report">{tr('Усі новини ПроМедіа ↗','All ProMedia news ↗')}</a></aside></div></>}</main><footer><a href={en?'/en':'/'}>{tr('Атлас Меда','Media Atlas')}</a><span>{tr('Проєкт ПроМедіа · Реєстр Нацради','A ProMedia project · National Council registry')}</span></footer></>;
}


