'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
type Article={title:string;url:string;publishedAt?:string;excerpt?:string};
type ProfileData={id:string;name:string;date:string;newsIds:string[];grouping:string;community:null|{id:string;website:string;description:string};entities:Record<string,{name:string;code:string}>;regions:{id:string;name:string}[];media:{id:string;names:string[];categories:string[];locations:{city:string;region:string}[];technologies:string[];details:{row:number;city:string;region:string;channel:string;frequency:string;territory:string;note:string}[]}[]};
const source='https://webportal.nrada.gov.ua/derzhavnyj-reyestr-sub-yektiv-informatsijnoyi-diyalnosti-u-sferi-telebachennya-i-radiomovlennya/';
const safeUrl=(s:string)=>{try{const u=new URL(s);return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch{return ''}};
export default function Profile({id}:{id:string}){
 const [profile,setProfile]=useState<ProfileData|null>(null),[error,setError]=useState(''),[news,setNews]=useState<Article[]>([]),[newsState,setNewsState]=useState('loading'),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const c=new AbortController();setProfile(null);setError('');if(!/^atlas-[a-z0-9-]+$/.test(id)){setError('Такої сторінки немає.');return}const bucket=id.slice(6,7);fetch('/data/brand-buckets/'+encodeURIComponent(bucket)+'.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error(r.status===404?'Такої сторінки немає.':'Не вдалося завантажити сторінку.');return r.json()}).then(v=>{const p=(v as Record<string,ProfileData>)[id];if(!p||p.id!==id||!Array.isArray(p.media)||!Array.isArray(p.newsIds))throw Error('Такої сторінки немає.');setProfile(p);document.title=p.name+' — Атлас Меда'}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[id]);
 useEffect(()=>{if(!profile)return;const c=new AbortController();setNews([]);setNewsState('loading');Promise.allSettled(profile.newsIds.map(mediaId=>fetch('https://news.promedia.report/api/articles?mediaId='+encodeURIComponent(mediaId)+'&limit=12',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('News unavailable');return r.json()}).then(v=>{const items=(v as {items?:Article[]}).items;if(!Array.isArray(items))throw Error('Invalid news');return items}))).then(results=>{if(c.signal.aborted)return;const items=results.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(a=>typeof a.title==='string'&&typeof a.url==='string'&&safeUrl(a.url).startsWith('https://news.promedia.report/article/'));const unique=[...new Map(items.map(a=>[a.url,a])).values()].sort((a,b)=>(Date.parse(b.publishedAt||'')||0)-(Date.parse(a.publishedAt||'')||0)).slice(0,12);setNews(unique);setNewsState(results.some(r=>r.status==='rejected')?(unique.length?'partial':'error'):'ready')});return()=>c.abort()},[profile,attempt]);
 return <><header className="topbar"><a className="atlas-wordmark" href="/">Атлас Меда<small>ПРОЄКТ ПРОМЕДІА</small></a><nav><a href="/">← Карта й каталог</a><a href="https://news.promedia.report">Новини ПроМедіа ↗</a></nav></header><main className="profile-page">{error?<section className="empty"><h1>{error}</h1><a href="/">Повернутися до каталогу</a></section>:!profile?<p role="status">Завантажуємо сторінку медіа…</p>:<><p className="eyebrow">ПУБЛІЧНА СТОРІНКА МЕДІАБРЕНДУ</p><h1>{profile.name}</h1><div className="profile-summary"><span>{profile.media.length} реєстрацій</span><span>{new Set(profile.media.flatMap(m=>m.categories)).size} видів діяльності</span><span>Реєстр на {profile.date}</span></div>{profile.community&&<><p className="profile-lead">{profile.community.description}</p><div className="profile-links">{safeUrl(profile.community.website)&&<a href={safeUrl(profile.community.website)} target="_blank" rel="noreferrer">Сайт медіа ↗</a>}<a href={'https://communities.promedia.report/media/?id='+encodeURIComponent(profile.community.id)}>Спільнота медіа ↗</a></div></>}
 <div className="profile-grid"><section className="profile-records"><h2>Реєстрації цього бренду</h2><p className="help">Кожен ідентифікатор збережено окремо разом із записами джерела.</p>{profile.media.map(m=><details key={m.id} className="registration"><summary><b>{m.id}</b><span>{m.categories.join('; ')}</span></summary><h3>Назва в реєстрі</h3><p>{m.names.join(' / ')||'Не зазначено'}</p><h3>Місцезнаходження</h3><p>{m.locations.map(l=>l.city+', '+(profile.regions.find(r=>r.id===l.region)?.name||l.region)).join('; ')||'Іноземне медіа'}</p><h3>Технологія / вид медіа</h3><p>{m.technologies.join('; ')||'Не зазначено'}</p>{m.details.map((d,i)=><details className="source-record" key={i}><summary>Рядок {d.row}{d.city?' · '+d.city:''}</summary>{Object.entries({'Населений пункт':d.city,'Область':d.region,'Канал':d.channel,'Частота':d.frequency,'Територія':d.territory,'Примітка':d.note}).filter(([,v])=>v).map(([k,v])=><p key={k}><b>{k}: </b>{v}</p>)}</details>)}</details>)}<h2>Реєстранти</h2>{Object.entries(profile.entities).map(([e,v])=><article key={e} className="registrant"><h3>{v.name}</h3>{v.code&&<p>ЄДРПОУ: {v.code}</p>}</article>)}<details className="method"><summary>Як об’єднано реєстрації</summary><p>{profile.grouping}</p><p>Однаковий власник сам по собі не об’єднує різні бренди. Схожі назви різних реєстрантів залишаються окремими до перевірки. Це сторінка за даними реєстру, а не підтвердження фактичної роботи чи структури власності.</p><a href={source}>Перевірити першоджерело ↗</a></details></section>
 <aside className="profile-news"><p className="eyebrow">НОВИНИ ПРО ЦЕ МЕДІА</p><h2>У фокусі ПроМедіа</h2><p className="help">Матеріали, які редакція ПроМедіа пов’язала з цим брендом.</p>{newsState==='loading'&&<p role="status">Завантажуємо новини…</p>}{newsState==='ready'&&!news.length&&<p className="news-empty">Пов’язаних публікацій поки немає.</p>}{(newsState==='error'||newsState==='partial')&&<div role="status"><p>{newsState==='partial'?'Частина новин тимчасово недоступна.':'Не вдалося завантажити новини.'}</p><Button variant="outline" onClick={()=>setAttempt(a=>a+1)}>Спробувати ще раз</Button></div>}{news.map(a=><article className="brand-news-item" key={a.url}>{a.publishedAt&&Number.isFinite(Date.parse(a.publishedAt))&&<time dateTime={a.publishedAt}>{new Date(a.publishedAt).toLocaleDateString('uk-UA')}</time>}<h3><a href={a.url} target="_blank" rel="noreferrer">{a.title} ↗</a></h3>{a.excerpt&&<p>{a.excerpt}</p>}</article>)}<a href="https://news.promedia.report">Усі новини ПроМедіа ↗</a></aside></div></>}</main><footer><a href="/">Атлас Меда</a><span>Проєкт ПроМедіа · Реєстр Нацради</span></footer></>;
}
